In [102]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

filepath = '/Users/thananpornsethjinda/Desktop/pulsar-pred/data/pulsar_data.csv'

test = pd.read_csv(filepath)




In [4]:
filepath = '/Users/thananpornsethjinda/Desktop/pulsar-pred/data/HTRU_2.csv'

df = pd.read_csv(filepath)

In [23]:
df2 = pd.read_csv('/Users/thananpornsethjinda/Desktop/pulsar-pred/data/pulsar_data_test.csv')
 


In [27]:
first_row = pd.DataFrame([df.columns.to_list()], columns=df.columns)

print(first_row)

actual_df = pd.concat([first_row, df]).reset_index(drop=True)

actual_df.columns = df2.columns

   140.5625  55.68378214  -0.234571412  -0.699648398  3.199832776  \
0  140.5625  55.68378214  -0.234571412  -0.699648398  3.199832776   

   19.11042633  7.975531794  74.24222492  0  
0  19.11042633  7.975531794  74.24222492  0  


In [98]:
actual_df

Mean of the integrated profile  \
0                            140.5625   
1                          102.507812   
2                          103.015625   
3                              136.75   
4                           88.726562   
...                               ...   
17893                      136.429688   
17894                      122.554688   
17895                      119.335938   
17896                      114.507812   
17897                         57.0625   

       Standard deviation of the integrated profile  \
0                                       55.68378214   
1                                          58.88243   
2                                         39.341649   
3                                         57.178449   
4                                         40.672225   
...                                             ...   
17893                                     59.847421   
17894                                     49.485605   
17895                                     59.935939   
17896                                       53.9024   
17897                                      85.79734   

       Excess kurtosis of the integrated profile  \
0                                   -0.234571412   
1                                       0.465318   
2                                       0.323328   
3                                      -0.068415   
4                                       0.600866   
...                                          ...   
17893                                  -0.187846   
17894                                   0.127978   
17895                                   0.159363   
17896                                   0.201161   
17897                                   1.406391   

       Skewness of the integrated profile  Mean of the DM-SNR curve  \
0                            -0.699648398               3.199832776   
1                               -0.515088                  1.677258   
2                                1.051164                  3.121237   
3                               -0.636238                  3.642977   
4                                1.123492                   1.17893   
...                                   ...                       ...   
17893                           -0.738123                  1.296823   
17894                            0.323061                 16.409699   
17895                           -0.743025                 21.430602   
17896                           -0.024789                  1.946488   
17897                             0.08952                 188.30602   

       Standard deviation of the DM-SNR curve  \
0                                 19.11042633   
1                                   14.860146   
2                                   21.744669   
3                                    20.95928   
4                                    11.46872   
...                                       ...   
17893                               12.166062   
17894                               44.626893   
17895                                  58.872   
17896                               13.381731   
17897                               64.712562   

       Excess kurtosis of the DM-SNR curve  Skewness of the DM-SNR curve  \
0                              7.975531794                   74.24222492   
1                                10.576487                     127.39358   
2                                 7.735822                     63.171909   
3                                 6.896499                     53.593661   
4                                14.269573                    252.567306   
...                                    ...                           ...   
17893                             15.45026                    285.931022   
17894                             2.945244                      8.297092   
17895                             2.499517                      4.595173   
17896                     

In [81]:
# making train test split (stratified)

from sklearn.model_selection import train_test_split

print(actual_df.columns[0:-1])

X = actual_df[actual_df.columns[0:-1]]

def to_float(x):
    return float(x)

X = X.applymap(to_float)

y = actual_df[actual_df.columns[-1]]

def to_int(x):
    return int(x)

y = y.apply(to_int)

y

Index([' Mean of the integrated profile',
       ' Standard deviation of the integrated profile',
       ' Excess kurtosis of the integrated profile',
       ' Skewness of the integrated profile', ' Mean of the DM-SNR curve',
       ' Standard deviation of the DM-SNR curve',
       ' Excess kurtosis of the DM-SNR curve',
       ' Skewness of the DM-SNR curve'],
      dtype='object')


/var/folders/19/sr0vg3y90ns0sp5j74zth4h80000gn/T/ipykernel_71639/1929150648.py:12: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X = X.applymap(to_float)


0        0
1        0
2        0
3        0
4        0
        ..
17893    0
17894    0
17895    0
17896    0
17897    0
Name: target_class, Length: 17898, dtype: int64

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)


In [83]:
X_train

Mean of the integrated profile  \
4644                        42.507812   
5419                       115.906250   
12212                      128.593750   
13140                       81.718750   
7612                        59.367188   
...                               ...   
6349                       139.539062   
12584                      140.437500   
15650                      114.882812   
4596                       100.429688   
4199                        80.437500   

       Standard deviation of the integrated profile  \
4644                                      34.301056   
5419                                      42.021653   
12212                                     48.619447   
13140                                     42.620773   
7612                                      38.205626   
...                                             ...   
6349                                      60.545941   
12584                                     46.453059   
15650                                     44.849509   
4596                                      46.227644   
4199                                      48.139730   

       Excess kurtosis of the integrated profile  \
4644                                    3.516712   
5419                                    0.187364   
12212                                  -0.069990   
13140                                   1.053643   
7612                                    2.731384   
...                                          ...   
6349                                   -0.488407   
12584                                   0.121573   
15650                                   0.437513   
4596                                    0.397975   
4199                                    1.606093   

       Skewness of the integrated profile  Mean of the DM-SNR curve  \
4644                            18.678145                 78.959030   
5419                             0.220270                  2.163043   
12212                           -0.120059                  2.479933   
13140                            2.167799                  3.020903   
7612                            10.864211                 35.949833   
...                                   ...                       ...   
6349                            -0.729511                192.659699   
12584                            0.030169                  1.512542   
15650                            0.531763                  2.572742   
4596                             0.164391                  2.605351   
4199                             2.362366                 32.723244   

       Standard deviation of the DM-SNR curve  \
4644                                71.684410   
5419                                16.979705   
12212                               16.560937   
13140                               20.885067   
7612                                61.943435   
...                                       ...   
6349                                78.932693   
12584                               13.934354   
15650                               15.707684   
4596                                17.646608   
4199                                65.511694   

       Excess kurtosis of the DM-SNR curve  Skewness of the DM-SNR curve  
4644                              0.641441                     -0.533831  
5419                              9.512104                    101.169582  
12212                             9.740289                    114.889976  
13140                             7.624972                     62.381735  
7612                              1.804810                      2.408786  
...                                    ...                           ...  
6349                             -1.623120                      1.166160  
12584                            12.659416                    182.183402  
15650                             9.863247                    122.649907  
4596                              9.

In [ ]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
X_train_processed = scale.fit_transform(X_train)
X_test_processed = scale.transform(X_test)



array([[-2.67946778, -1.79478007,  2.8595421 , ...,  2.34299093,
        -1.70589651, -0.99075829],
       [ 0.18953379, -0.66026852, -0.27355262, ..., -0.47731643,
         0.26237997, -0.03944414],
       [ 0.68546338,  0.30925141, -0.51573674, ..., -0.49890602,
         0.31301109,  0.08889377],
       ...,
       [ 0.14952961, -0.24472617, -0.03814834, ..., -0.54289561,
         0.34029374,  0.16147868],
       [-0.41541481, -0.04221465, -0.0753563 , ..., -0.44293414,
         0.19543697, -0.0560525 ],
       [-1.19687038,  0.23875892,  1.06154722, ...,  2.02475585,
        -1.43672236, -0.96586768]], shape=(14318, 8))

In [116]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train_processed, np.array(y_train))

lr.coef_

array([[ 0.57572672, -0.12538257,  6.08141343, -3.05067217, -0.82602568,
         0.88060627, -0.20221233, -0.32556464]])

In [88]:
y_pred = lr.predict(X_test_processed)

In [95]:
from sklearn.metrics import roc_auc_score, confusion_matrix

roc_auc_score(y_true=y_test, y_score=y_pred)

confusion_matrix(y_true=y_test, y_pred=y_pred, normalize='true')



array([[0.99507995, 0.00492005],
       [0.17378049, 0.82621951]])

dtype('O')

In [76]:
print(type(X.iloc[0, 2]))

<class 'str'>


In [77]:
def to_float(x):
    return float(x)

X = X.applymap(to_float)


/var/folders/19/sr0vg3y90ns0sp5j74zth4h80000gn/T/ipykernel_71639/51473747.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X = X.applymap(to_float)


In [78]:
X

Mean of the integrated profile  \
0                          140.562500   
1                          102.507812   
2                          103.015625   
3                          136.750000   
4                           88.726562   
...                               ...   
17893                      136.429688   
17894                      122.554688   
17895                      119.335938   
17896                      114.507812   
17897                       57.062500   

       Standard deviation of the integrated profile  \
0                                         55.683782   
1                                         58.882430   
2                                         39.341649   
3                                         57.178449   
4                                         40.672225   
...                                             ...   
17893                                     59.847421   
17894                                     49.485605   
17895                                     59.935939   
17896                                     53.902400   
17897                                     85.797340   

       Excess kurtosis of the integrated profile  \
0                                      -0.234571   
1                                       0.465318   
2                                       0.323328   
3                                      -0.068415   
4                                       0.600866   
...                                          ...   
17893                                  -0.187846   
17894                                   0.127978   
17895                                   0.159363   
17896                                   0.201161   
17897                                   1.406391   

       Skewness of the integrated profile  Mean of the DM-SNR curve  \
0                               -0.699648                  3.199833   
1                               -0.515088                  1.677258   
2                                1.051164                  3.121237   
3                               -0.636238                  3.642977   
4                                1.123492                  1.178930   
...                                   ...                       ...   
17893                           -0.738123                  1.296823   
17894                            0.323061                 16.409699   
17895                           -0.743025                 21.430602   
17896                           -0.024789                  1.946488   
17897                            0.089520                188.306020   

       Standard deviation of the DM-SNR curve  \
0                                   19.110426   
1                                   14.860146   
2                                   21.744669   
3                                   20.959280   
4                                   11.468720   
...                                       ...   
17893                               12.166062   
17894                               44.626893   
17895                               58.872000   
17896                               13.381731   
17897                               64.712562   

       Excess kurtosis of the DM-SNR curve  Skewness of the DM-SNR curve  
0                                 7.975532                     74.242225  
1                                10.576487                    127.393580  
2                                 7.735822                     63.171909  
3                                 6.896499                     53.593661  
4                                14.269573                    252.567306  
...                                    ...                           ...  
17893                            15.450260                    285.931022  
17894                             2.945244                      8.297092  
17895                             2.499517                      4.595173  
17896                            10.

In [106]:
X_train_processed

array([[-2.67946778, -1.79478007,  2.8595421 , ...,  2.34299093,
        -1.70589651, -0.99075829],
       [ 0.18953379, -0.66026852, -0.27355262, ..., -0.47731643,
         0.26237997, -0.03944414],
       [ 0.68546338,  0.30925141, -0.51573674, ..., -0.49890602,
         0.31301109,  0.08889377],
       ...,
       [ 0.14952961, -0.24472617, -0.03814834, ..., -0.54289561,
         0.34029374,  0.16147868],
       [-0.41541481, -0.04221465, -0.0753563 , ..., -0.44293414,
         0.19543697, -0.0560525 ],
       [-1.19687038,  0.23875892,  1.06154722, ...,  2.02475585,
        -1.43672236, -0.96586768]], shape=(14318, 8))

In [115]:
for (row_X, row_Y) in (X_train_processed, np.array(y_train)):
    print(row_X) + print(row_Y)

ValueError: too many values to unpack (expected 2)

In [120]:
from sympy import symbols

loss_func = []

theta = symbols('theta:8') 

def sigmoid(y): 
    return 1/(1+np.e**(-y))

for index in range(len(X_train_processed)): 

    y = y_train[index]

    loss_func.append(-np.log(sigmoid(np.dot(theta, X_train_processed[index]))**y*(1-sigmoid(np.dot(theta, X_train_processed[index]))**y)))



TypeError: loop of ufunc does not support argument 0 of type Zero which has no callable log method

-2.67946778418837*theta0 - 1.79478006965797*theta1 + 2.85954210116719*theta2 + 2.73643746373258*theta3 + 2.31114217849688*theta4 + 2.34299092847681*theta5 - 1.70589651240479*theta6 - 0.99075828538603*theta7

In [141]:
def sigmoid(y): 
    return 1/(1+np.e**(-y))

def f(t1, t2, t3, t4, t5, t6, t7, t8):

    loss_func = []

    z = np.array([t1, t2, t3, t4, t5, t6, t7, t8])

    for index in range(len(X_train_processed)): 

        h = sigmoid(np.dot(z, X_train_processed[index]))

        h = np.clip(h, 1e-15, 1 - 1e-15)

        y = np.array(y_train)[index]

        loss_func.append(-np.log(h**y*(1-h)**(1-y)))

    return np.sum(loss_func)


In [142]:
f(0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.3, 0.1)

np.float64(10123.79967952296)